apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: search-agent
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/network-interfaces: '[{"network":"search-demo-vpc","subnetwork":"search-demo-vpc"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      serviceAccountName: search-backend-sa@prop-search-demo.iam.gserviceaccount.com
      containers:
      - name: agent
        image: europe-west3-docker.pkg.dev/prop-search-demo/search-app-repo/search-agent:20260407-153534
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "prop-search-demo"
        - name: GOOGLE_CLOUD_REGION
          value: "europe-west3"
        - name: GOOGLE_CLOUD_LOCATION
          value: "global"
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: "true"
        - name: TOOLBOX_URL
          value: "https://search-toolbox-iiznqhigna-ey.a.run.app"
